name: build-and-test

on:
  pull_request:
    branches:
      - master
      - develop
      - next-release
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install Dependencies 👨🏻‍💻
        uses: ./.github/actions/install-dependencies

      - name: Setup Turbo cache 🏎️
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Run linter 🧹
        run: pnpm run lint --cache-dir=.turbo

      - name: Build Library 👷
        run: pnpm run build --cache-dir=.turbo

      - name: Run tests 🧪
        uses: cypress-io/github-action@v5
        with:
          install-command: pnpm cypress install
          command: pnpm run test --cache-dir=.turbo
          browser: chrome
          component: true
